# Generated by Django 3.1.5 on 2021-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listning',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Appliances'), ('2', 'Apps & Games'), ('3', 'Arts, Crafts, & Sewing'), ('4', 'Automotive Parts & Accessories'), ('5', 'Baby'), ('6', 'Beauty & Personal Care'), ('7', 'Books'), ('8', 'CDs & Vinyl'), ('9', 'Cell Phones & Accessories'), ('10', 'Clothing, Shoes and Jewelry'), ('11', 'Collectibles & Fine Art'), ('12', 'Computers'), ('13', 'Electronics'), ('14', 'Garden & Outdoor'), ('15', 'Grocery & Gourmet Food'), ('16', 'Handmade'), ('17', 'Health, Household & Baby Care'), ('18', 'Home & Kitchen'), ('19', 'Industrial & Scientific'), ('20', 'Kindle'), ('21', 'Luggage & Travel Gear'), ('22', 'Movies & TV'), ('23', 'Musical Instruments'), ('24', 'Office Products'), ('25', 'Sports & Outdoors'), ('26', 'Tools & Home Improvement'), ('27', 'Toys & Games'), ('28', 'Video Games'), ('29', 'None')], default='None'),
        ),
    ]
