# Generated by Django 3.1.5 on 2021-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listning',
            name='category',
            field=models.CharField(choices=[('Appliances', 'Appliances'), ('Apps & Games', 'Apps & Games'), ('Arts, Crafts, & Sewing', 'Arts, Crafts, & Sewing'), ('Automotive Parts & Accessories', 'Automotive Parts & Accessories'), ('Baby', 'Baby'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books', 'Books'), ('CDs & Vinyl', 'CDs & Vinyl'), ('Cell Phones & Accessories', 'Cell Phones & Accessories'), ('Clothing, Shoes and Jewelry', 'Clothing, Shoes and Jewelry'), ('Collectibles & Fine Art', 'Collectibles & Fine Art'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ('Garden & Outdoor', 'Garden & Outdoor'), ('Grocery & Gourmet Food', 'Grocery & Gourmet Food'), ('Handmade', 'Handmade'), ('Health, Household & Baby Care', 'Health, Household & Baby Care'), ('Home & Kitchen', 'Home & Kitchen'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Kindle', 'Kindle'), ('Luggage & Travel Gear', 'Luggage & Travel Gear'), ('Movies & TV', 'Movies & TV'), ('Musical Instruments', 'Musical Instruments'), ('Office Products', 'Office Products'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Toys & Games', 'Toys & Games'), ('Video Games', 'Video Games'), ('None', 'None')], default='None', max_length=64),
        ),
    ]
