# Generated by Django 3.1.5 on 2021-09-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210830_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listning',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
