# Generated by Django 3.1.5 on 2021-09-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210911_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listning',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
