# Generated by Django 3.1.5 on 2022-07-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_follow_like_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
